# Generated by Django 4.1.2 on 2022-12-31 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_remove_has_id_alter_has_pkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='has',
            name='paid',
            field=models.DecimalField(decimal_places=2, default=500, max_digits=10),
            preserve_default=False,
        ),
    ]
